"""Curated beginner-friendly recipes used by the website."""


def recipe(slug, name, cuisine, minutes, description, ingredients, steps, tip, tags, featured=False):
    return {
        "slug": slug,
        "name": name,
        "cuisine": cuisine,
        "minutes": minutes,
        "description": description,
        "ingredients": ingredients,
        "steps": steps,
        "tip": tip,
        "tags": tags,
        "featured": featured,
        "servings": 2,
        "difficulty": "Easy",
        "image": f"images/{slug}.jpg",
    }


RECIPES = [
    recipe("chicken-fried-rice", "Chicken Fried Rice", "Chinese", 25, "Golden, savoury rice with tender chicken and vegetables.", ["2 cups cold cooked rice", "200 g chicken thigh, diced", "2 eggs, beaten", "1 cup frozen mixed vegetables", "2 tbsp light soy sauce", "1 tsp sesame oil", "2 tbsp neutral oil", "2 spring onions, sliced"], ["Break up the cold rice with clean fingers so no large clumps remain.", "Heat 1 tbsp oil in a large pan on medium-high. Cook chicken for 5–6 minutes until no pink remains; move it to a plate.", "Add the remaining oil. Pour in eggs and stir for 30 seconds until softly set.", "Add vegetables and rice. Stir-fry for 3 minutes, pressing out clumps.", "Return chicken. Add soy sauce and sesame oil around the hot edge of the pan; toss for 1 minute.", "Turn off heat, add spring onions, taste, and serve hot."], "Cold, day-old rice stays separate. Fresh warm rice can turn mushy.", ["rice", "chicken", "quick"], True),
    recipe("beef-chow-mein", "Beef Chow Mein", "Chinese", 30, "Slippery noodles, crisp vegetables, and juicy beef in a glossy sauce.", ["250 g fresh egg noodles", "200 g beef, thinly sliced", "2 cups shredded cabbage", "1 carrot, cut into matchsticks", "2 tbsp soy sauce", "1 tbsp oyster sauce", "1 tsp sugar", "2 tbsp neutral oil"], ["Mix soy sauce, oyster sauce, sugar, and 2 tbsp water.", "Prepare noodles according to the packet, drain, and rinse briefly.", "Heat 1 tbsp oil on high. Cook beef in one layer for 90 seconds per side; remove.", "Add remaining oil, cabbage, and carrot. Stir-fry for 2 minutes.", "Add noodles, beef, and sauce. Toss with two utensils for 2 minutes until glossy."], "Slice beef across the grain; the short fibres make every bite tender.", ["noodles", "beef", "quick"], True),
    recipe("pork-dumplings", "Crispy Pork Dumplings", "Chinese", 40, "Juicy dumplings with crisp golden bottoms and a foolproof steam-fry method.", ["20 round dumpling wrappers", "250 g pork mince", "1 cup finely chopped cabbage", "2 spring onions, sliced", "1 tbsp soy sauce", "1 tsp sesame oil", "1 tbsp neutral oil", "1/3 cup water"], ["Mix pork, cabbage, spring onions, soy sauce, and sesame oil until sticky.", "Put 1 heaped tsp filling in each wrapper. Wet the edge, fold, and pinch firmly closed.", "Heat oil in a non-stick pan on medium. Arrange dumplings flat-side down and cook 2 minutes.", "Add water and immediately cover. Steam for 6 minutes.", "Remove lid and cook 2–3 minutes until the water is gone and bottoms are crisp."], "Do not overfill the wrappers; a tight seal matters more than fancy pleats.", ["dumplings", "pork", "snack"]),
    recipe("teriyaki-chicken", "Teriyaki Chicken", "Japanese", 25, "Sticky-sweet glazed chicken with a deeply savoury finish.", ["400 g boneless chicken thighs", "2 tbsp soy sauce", "2 tbsp mirin", "1 tbsp brown sugar", "1 tsp grated ginger", "1 tsp neutral oil", "2 bowls cooked rice", "1 tsp sesame seeds"], ["Mix soy sauce, mirin, sugar, and ginger until the sugar dissolves.", "Pat chicken dry. Heat oil in a pan on medium-high and place chicken smooth-side down.", "Cook 5 minutes, turn, and cook another 4 minutes until cooked through.", "Lower heat. Pour in sauce and turn chicken repeatedly for 2–3 minutes until glossy.", "Slice chicken and spoon the pan sauce over rice. Sprinkle with sesame seeds."], "Lower the heat before adding sugar-rich sauce so it thickens without burning.", ["chicken", "rice", "quick"], True),
    recipe("miso-ramen", "Easy Miso Ramen", "Japanese", 30, "A creamy, savoury noodle bowl made with supermarket ingredients.", ["2 packs ramen noodles", "750 ml chicken stock", "2 tbsp white miso", "1 tbsp soy sauce", "1 tsp sesame oil", "2 eggs", "1 cup corn", "2 spring onions, sliced"], ["Boil eggs for 7 minutes, cool in cold water, peel, and halve.", "Bring stock to a gentle simmer. Whisk miso with a ladle of hot stock in a small bowl.", "Pour the miso mixture back in. Add soy sauce and sesame oil; keep below a hard boil.", "Cook noodles separately according to the packet and divide between bowls.", "Pour over broth and top with egg, corn, and spring onions."], "Never boil miso hard; gentle heat protects its smooth flavour.", ["noodles", "soup", "vegetarian"]),
    recipe("salmon-sushi-bowl", "Salmon Sushi Bowl", "Japanese", 20, "All the fresh flavours of sushi with none of the rolling.", ["250 g skinless salmon, cubed", "2 cups cooked sushi rice", "1 cucumber, sliced", "1 avocado, sliced", "2 tbsp soy sauce", "1 tsp sesame oil", "1 tsp rice vinegar", "1 sheet nori, snipped"], ["Use salmon sold as safe for raw eating, or cook it fully in a pan for 5 minutes.", "Mix soy sauce and sesame oil; coat the salmon.", "Stir rice vinegar through warm rice and divide between bowls.", "Arrange salmon, cucumber, and avocado on top.", "Finish with nori and any remaining sauce."], "If the fish label does not clearly say it is suitable for raw consumption, cook it.", ["salmon", "rice", "no-cook"], True),
    recipe("bibimbap", "Weeknight Bibimbap", "Korean", 35, "Colourful rice bowls topped with vegetables, beef, egg, and spicy sauce.", ["2 bowls cooked rice", "200 g beef mince", "1 carrot, shredded", "1 zucchini, sliced", "2 cups baby spinach", "2 eggs", "2 tbsp gochujang", "1 tbsp soy sauce", "2 tsp sesame oil"], ["Mix gochujang with 1 tbsp water and 1 tsp sesame oil.", "Cook carrot, zucchini, and spinach separately in a lightly oiled pan, 2–3 minutes each.", "Cook beef with soy sauce for 5 minutes until browned and no pink remains.", "Fry eggs until whites are set.", "Divide rice into bowls. Arrange vegetables and beef in sections, top with egg and sauce, then mix before eating."], "Cook each vegetable separately so the colours stay bright and nothing turns watery.", ["rice", "beef", "spicy"]),
    recipe("korean-fried-chicken", "Korean Crispy Chicken", "Korean", 40, "Crunchy chicken bites coated in a sweet, spicy, sticky glaze.", ["450 g chicken thigh, bite-size", "1/2 cup cornflour", "1/2 tsp salt", "3 tbsp gochujang", "2 tbsp honey", "1 tbsp soy sauce", "1 tsp rice vinegar", "3 tbsp neutral oil"], ["Pat chicken very dry, then toss with cornflour and salt.", "Mix gochujang, honey, soy sauce, vinegar, and 2 tbsp water.", "Heat oil in a wide pan on medium-high. Cook chicken in one layer for 5 minutes per side.", "Check the thickest piece has no pink centre, then move chicken to a plate.", "Wipe the pan carefully. Simmer sauce for 1 minute, add chicken, and toss until coated."], "Crowding traps steam. Cook in two batches if the pieces cannot sit in one layer.", ["chicken", "spicy", "crispy"]),
    recipe("beef-bulgogi", "Beef Bulgogi", "Korean", 25, "Caramelised marinated beef with sweet pear, soy, and sesame.", ["350 g thinly sliced beef", "3 tbsp soy sauce", "2 tbsp grated pear or apple", "1 tbsp brown sugar", "1 tsp sesame oil", "2 garlic cloves, grated", "1/2 onion, sliced", "2 bowls cooked rice"], ["Mix soy sauce, pear, sugar, sesame oil, and garlic.", "Add beef and onion; mix and leave for 10 minutes.", "Heat a wide pan on high until very hot.", "Cook beef in two batches, 2–3 minutes each, letting the edges brown.", "Serve immediately over rice."], "Freeze the beef for 20 minutes first—it becomes much easier to slice thinly.", ["beef", "rice", "quick"]),
    recipe("butter-chicken", "Easy Butter Chicken", "Indian", 40, "Creamy tomato chicken with gentle spice and a rich restaurant-style sauce.", ["400 g chicken thigh, cubed", "1 tbsp curry powder", "1 tsp garam masala", "2 tbsp butter", "2 garlic cloves, grated", "400 g canned crushed tomatoes", "150 ml cooking cream", "1/2 tsp salt"], ["Toss chicken with curry powder and half the salt.", "Melt 1 tbsp butter in a pan on medium-high. Cook chicken for 6 minutes; remove.", "Add remaining butter and garlic. Stir for 30 seconds.", "Add tomatoes and garam masala. Simmer uncovered for 10 minutes.", "Return chicken and simmer 5 minutes until cooked through.", "Turn heat low, stir in cream, taste for salt, and warm without boiling."], "Add cream only on low heat so the sauce stays smooth.", ["chicken", "curry", "creamy"], True),
    recipe("chana-masala", "Chana Masala", "Indian", 30, "A comforting chickpea curry that is cheap, hearty, and full of flavour.", ["2 cans chickpeas, drained", "1 onion, diced", "2 garlic cloves, grated", "1 tbsp curry powder", "1 tsp ground cumin", "400 g canned crushed tomatoes", "1 tbsp neutral oil", "1/2 tsp salt"], ["Heat oil on medium. Cook onion with a pinch of salt for 6 minutes until soft.", "Add garlic, curry powder, and cumin. Stir for 30 seconds.", "Add tomatoes and chickpeas. Stir and bring to a gentle simmer.", "Cook uncovered for 15 minutes, stirring every few minutes.", "Crush a spoonful of chickpeas against the pan to thicken, then taste for salt."], "Spices burn quickly. Have the tomatoes open before adding spices.", ["vegan", "chickpeas", "curry"]),
    recipe("chicken-biryani", "One-Pot Chicken Biryani", "Indian", 50, "Fragrant spiced rice and tender chicken made in one dependable pot.", ["350 g chicken thighs", "1.5 cups basmati rice", "1 onion, sliced", "2 tbsp biryani spice blend", "2.25 cups chicken stock", "1/2 cup plain yogurt", "2 tbsp neutral oil", "1/2 tsp salt"], ["Rinse rice in a sieve until the water is mostly clear; drain well.", "Mix chicken with yogurt, spice blend, and salt.", "Heat oil in a heavy pot. Cook onion for 8 minutes until golden; set half aside.", "Add chicken and cook 4 minutes, turning once.", "Scatter rice over chicken and pour in stock. Do not stir.", "Bring to a simmer, cover tightly, and cook on very low heat for 18 minutes.", "Turn off heat, rest covered for 10 minutes, then fluff and top with reserved onion."], "The covered rest is part of cooking—do not lift the lid early.", ["chicken", "rice", "one-pot"]),
    recipe("beef-pho", "Shortcut Beef Pho", "Vietnamese", 35, "A fragrant, clear noodle soup with tender beef and fresh herbs.", ["200 g very thin beef slices", "200 g flat rice noodles", "1 litre beef stock", "1 onion, halved", "3 cm ginger, sliced", "1 cinnamon stick", "2 star anise", "2 tbsp fish sauce", "1 cup bean sprouts", "Fresh mint or coriander"], ["Char onion and ginger cut-side down in a dry pot for 4 minutes.", "Add stock, cinnamon, and star anise. Simmer gently for 20 minutes.", "Prepare noodles according to the packet and divide between deep bowls.", "Add fish sauce to broth and taste. Remove whole spices.", "Lay raw beef slices over noodles and pour boiling-hot broth directly on top.", "Add bean sprouts and herbs. Serve immediately."], "Beef must be paper-thin so the boiling broth cooks it. Otherwise, simmer it in the broth first.", ["soup", "beef", "noodles"]),
    recipe("banh-mi", "Quick Chicken Banh Mi", "Vietnamese", 25, "A crisp baguette packed with savoury chicken, pickles, herbs, and chilli mayo.", ["2 small baguettes", "250 g chicken thigh, sliced", "1 tbsp soy sauce", "1 carrot, shredded", "1/2 cucumber, sliced", "2 tbsp rice vinegar", "2 tbsp mayonnaise", "1 tsp chilli sauce", "Fresh coriander"], ["Mix carrot with vinegar and a pinch each of sugar and salt; leave 10 minutes.", "Coat chicken with soy sauce. Cook in a hot lightly oiled pan for 6–7 minutes until no pink remains.", "Mix mayonnaise and chilli sauce.", "Split and lightly toast baguettes.", "Spread with chilli mayo and fill with chicken, drained carrot, cucumber, and coriander."], "Drain the quick pickle well or it will make the bread soggy.", ["sandwich", "chicken", "quick"]),
    recipe("vietnamese-spring-rolls", "Fresh Spring Rolls", "Vietnamese", 30, "Cool, crunchy rice-paper rolls with prawns, noodles, and herbs.", ["8 rice-paper wrappers", "16 cooked prawns, halved", "100 g rice vermicelli", "1 carrot, cut into matchsticks", "1/2 cucumber, cut into matchsticks", "1 cup lettuce, shredded", "Fresh mint", "Sweet chilli sauce, to serve"], ["Prepare vermicelli according to the packet, rinse cold, and drain very well.", "Fill a wide shallow dish with warm—not hot—water.", "Dip one wrapper for 5 seconds; it should still feel slightly firm.", "Place fillings across the lower third, leaving a border.", "Fold the bottom over filling, fold sides inward, then roll tightly.", "Repeat one at a time and keep rolls separated."], "Rice paper keeps softening after dipping. Remove it while it still feels slightly firm.", ["prawns", "fresh", "no-cook"]),
    recipe("nasi-goreng", "Nasi Goreng", "Indonesian", 25, "Smoky Indonesian fried rice with sweet soy and a crispy fried egg.", ["2 cups cold cooked rice", "200 g chicken, diced", "2 eggs", "2 tbsp kecap manis", "1 tbsp soy sauce", "1 garlic clove, grated", "1 cup shredded cabbage", "2 tbsp neutral oil"], ["Mix kecap manis and soy sauce. Break up cold rice.", "Heat 1 tbsp oil on high. Cook chicken for 5 minutes until done.", "Add garlic and cabbage; stir-fry 1 minute.", "Add rice and sauce. Toss for 3 minutes until hot and evenly brown.", "In another pan, fry eggs in remaining oil until edges are crisp.", "Serve rice topped with an egg."], "Kecap manis is thick sweet soy sauce; regular soy is not a direct substitute.", ["rice", "chicken", "quick"]),
    recipe("satay-chicken", "Chicken Satay", "Indonesian", 35, "Charred chicken skewers with a creamy, tangy peanut sauce.", ["400 g chicken thigh, strips", "2 tbsp soy sauce", "1 tsp curry powder", "1 tbsp honey", "1 tbsp neutral oil", "3 tbsp peanut butter", "100 ml coconut milk", "1 tsp lime juice"], ["If using wooden skewers, soak them in water for 20 minutes.", "Mix chicken with soy sauce, curry powder, honey, and oil.", "Thread chicken loosely onto skewers.", "Cook in a hot grill pan for 4–5 minutes per side until cooked through.", "Warm peanut butter and coconut milk in a small pan, stirring smooth. Add lime juice.", "Serve skewers with sauce on the side."], "Leave tiny gaps between chicken pieces so heat reaches every surface.", ["chicken", "peanut", "skewers"]),
    recipe("laksa", "Easy Coconut Laksa", "Malaysian", 35, "Creamy, spicy coconut noodle soup with chicken and prawns.", ["200 g rice noodles", "200 g chicken, sliced", "150 g peeled prawns", "2 tbsp laksa or red curry paste", "400 ml coconut milk", "500 ml chicken stock", "1 tbsp fish sauce", "1 cup bean sprouts", "1 lime"], ["Prepare noodles according to the packet and divide between bowls.", "Cook curry paste in a pot with 1 tbsp oil for 1 minute.", "Add coconut milk and stock slowly while stirring. Bring to a gentle simmer.", "Add chicken and simmer 7 minutes.", "Add prawns and cook 3 minutes until opaque and curled.", "Stir in fish sauce. Pour over noodles and top with sprouts and lime."], "Once coconut milk is added, use a gentle simmer rather than a violent boil.", ["soup", "noodles", "spicy"]),
    recipe("hokkien-mee", "Easy Hokkien Mee", "Malaysian", 30, "Thick noodles tossed with prawns and greens in a dark savoury sauce.", ["400 g thick yellow noodles", "200 g peeled prawns", "2 cups chopped bok choy", "2 tbsp dark soy sauce", "1 tbsp light soy sauce", "1 tbsp oyster sauce", "1 tsp sugar", "2 cloves garlic, sliced", "2 tbsp neutral oil"], ["Mix both soy sauces, oyster sauce, sugar, and 3 tbsp water.", "Rinse noodles briefly under warm water and loosen them.", "Heat oil on high. Cook prawns for 2 minutes; remove.", "Add garlic and bok choy stems; stir-fry 1 minute.", "Add noodles, sauce, leafy greens, and prawns. Toss for 3 minutes until glossy and hot."], "Loosen noodles before they enter the pan; forcing a solid block will tear them.", ["noodles", "prawns", "quick"]),
    recipe("singapore-noodles", "Singapore Noodles", "Singaporean", 30, "Bouncy rice noodles with curry, prawns, egg, and crisp vegetables.", ["200 g thin rice vermicelli", "150 g peeled prawns", "2 eggs, beaten", "1 bell pepper, sliced", "1 carrot, shredded", "1.5 tbsp curry powder", "2 tbsp soy sauce", "2 tbsp neutral oil"], ["Soak noodles according to the packet, drain well, and cut twice with scissors.", "Heat 1 tbsp oil in a wok. Scramble eggs until just set; remove.", "Add remaining oil and prawns. Cook 2–3 minutes; remove.", "Stir-fry pepper and carrot for 2 minutes. Add curry powder and stir 20 seconds.", "Add noodles, soy sauce, egg, and prawns. Toss for 2 minutes until evenly yellow and hot."], "Drain the noodles thoroughly; excess water dilutes the curry flavour.", ["noodles", "prawns", "quick"]),
    recipe("pad-thai", "Foolproof Pad Thai", "Thai", 30, "Tangy, savoury rice noodles with prawns, egg, peanuts, and lime.", ["200 g flat rice noodles", "180 g peeled prawns", "2 eggs", "2 tbsp fish sauce", "2 tbsp brown sugar", "2 tbsp lime juice", "1 cup bean sprouts", "3 tbsp crushed peanuts", "2 tbsp neutral oil"], ["Soak noodles in room-temperature water until bendable but still firm; drain.", "Mix fish sauce, sugar, lime juice, and 3 tbsp water.", "Heat 1 tbsp oil on medium-high. Cook prawns for 2–3 minutes; remove.", "Add remaining oil and eggs. Scramble for 30 seconds.", "Add noodles and sauce. Toss for 3–4 minutes until noodles are tender.", "Return prawns, add sprouts, and toss 30 seconds. Top with peanuts."], "Do not boil the noodles first; soaking keeps them from becoming mushy in the pan.", ["noodles", "prawns", "quick"], True),
    recipe("thai-green-curry", "Thai Green Curry", "Thai", 35, "A fragrant coconut curry with tender chicken and crisp vegetables.", ["400 g chicken thigh, sliced", "2 tbsp green curry paste", "400 ml coconut milk", "1 bell pepper, sliced", "1 cup green beans", "1 tbsp fish sauce", "1 tsp brown sugar", "Fresh basil"], ["Spoon the thick coconut cream from the top of the can into a pan; cook 2 minutes.", "Add curry paste and stir for 1 minute until fragrant.", "Add chicken and stir for 3 minutes.", "Pour in remaining coconut milk. Simmer gently for 10 minutes.", "Add pepper and beans; simmer 5 minutes.", "Season with fish sauce and sugar, then stir in basil off the heat."], "Curry pastes vary in heat. Start with less and add more after tasting.", ["curry", "chicken", "spicy"], True),
    recipe("tom-yum-goong", "Tom Yum Goong", "Thai", 30, "Bright hot-and-sour prawn soup with lemongrass, lime, and chilli.", ["300 g peeled prawns", "750 ml chicken stock", "2 lemongrass stalks, bruised", "4 slices galangal or ginger", "200 g mushrooms, halved", "2 tbsp fish sauce", "2 tbsp lime juice", "1–2 tsp chilli paste"], ["Bring stock, lemongrass, and galangal to a gentle boil for 10 minutes.", "Add mushrooms and simmer 4 minutes.", "Add prawns and cook 2–3 minutes until pink and opaque.", "Turn off heat. Stir in fish sauce, lime juice, and chilli paste.", "Taste: add lime for sourness, fish sauce for salt, or chilli for heat."], "Add lime juice after turning off the heat so it stays fresh and bright.", ["soup", "prawns", "spicy"], True),
    recipe("thai-basil-chicken", "Thai Basil Chicken", "Thai", 20, "A fast, punchy minced chicken stir-fry with basil and chilli.", ["350 g chicken mince", "3 garlic cloves, chopped", "1 red chilli, sliced", "1 tbsp oyster sauce", "1 tbsp soy sauce", "1 tsp fish sauce", "1 tsp sugar", "1 cup basil leaves", "2 tbsp neutral oil"], ["Mix oyster sauce, soy sauce, fish sauce, sugar, and 2 tbsp water.", "Heat oil on high. Add garlic and chilli; stir for 20 seconds.", "Add chicken and break it into small pieces. Cook 5–6 minutes until no pink remains.", "Pour in sauce and toss for 1 minute.", "Turn off heat, fold in basil until wilted, and serve over rice."], "Have every ingredient ready before heating the pan; this cooks very fast.", ["chicken", "stir-fry", "quick"]),
    recipe("massaman-curry", "Easy Massaman Curry", "Thai", 50, "A mild, warmly spiced coconut curry with chicken, potato, and peanuts.", ["400 g chicken thighs", "2 tbsp massaman curry paste", "400 ml coconut milk", "2 potatoes, 2 cm cubes", "1 small onion, wedges", "2 tbsp fish sauce", "1 tbsp brown sugar", "3 tbsp roasted peanuts"], ["Cook curry paste with 3 tbsp coconut milk in a pot for 1 minute.", "Add chicken and stir for 3 minutes.", "Add remaining coconut milk, potatoes, onion, and 150 ml water.", "Bring to a gentle simmer, cover, and cook 25 minutes.", "Check potatoes with a knife; they should be soft. Stir in fish sauce and sugar.", "Top with peanuts and serve."], "Keep potato pieces the same size so they finish cooking together.", ["curry", "chicken", "mild"]),
    recipe("thai-pineapple-fried-rice", "Thai Pineapple Fried Rice", "Thai", 25, "Sweet-savoury fried rice with juicy pineapple, cashews, and curry spice.", ["2 cups cold cooked rice", "1 cup pineapple chunks, drained", "150 g peeled prawns", "2 eggs", "1 tsp curry powder", "1.5 tbsp fish sauce", "1/3 cup cashews", "2 tbsp neutral oil"], ["Break up rice and pat pineapple dry with paper towel.", "Heat 1 tbsp oil on high. Cook prawns for 2–3 minutes; remove.", "Add remaining oil and eggs; scramble for 30 seconds.", "Add rice and curry powder. Toss for 2 minutes.", "Add pineapple, prawns, fish sauce, and cashews. Toss for 1–2 minutes until hot."], "Dry pineapple prevents wet, soggy rice.", ["rice", "prawns", "quick"]),
    recipe("panang-beef", "Panang Beef Curry", "Thai", 35, "A thick, rich red curry with tender beef, coconut, and lime leaf.", ["350 g thinly sliced beef", "2 tbsp Panang curry paste", "400 ml coconut milk", "1 tbsp fish sauce", "1 tsp brown sugar", "4 makrut lime leaves, finely sliced", "1 bell pepper, sliced", "Fresh basil"], ["Cook curry paste with 3 tbsp thick coconut cream for 1 minute.", "Add half the remaining coconut milk and bring to a gentle simmer.", "Add beef and cook 5 minutes, stirring occasionally.", "Add remaining coconut milk and pepper; simmer 6 minutes.", "Season with fish sauce and sugar. Add lime leaves and basil off the heat."], "Slice beef thinly across the grain and do not simmer it longer than needed.", ["curry", "beef", "spicy"]),
    recipe("larb-gai", "Larb Gai", "Thai", 25, "A lively minced chicken salad with lime, herbs, chilli, and toasted rice.", ["350 g chicken mince", "2 tbsp lime juice", "1.5 tbsp fish sauce", "1 tsp sugar", "1/2 red onion, thinly sliced", "1 cup mint leaves", "1 tbsp toasted rice powder", "Chilli flakes, to taste"], ["Put chicken and 2 tbsp water in a pan on medium heat.", "Stir and break up chicken for 6–7 minutes until fully cooked.", "Turn off heat and let it cool for 2 minutes.", "Stir in lime juice, fish sauce, sugar, onion, and chilli.", "Fold in mint and toasted rice powder just before serving."], "Dress the chicken while warm, not scorching hot, so the herbs stay fresh.", ["chicken", "salad", "quick"]),
    recipe("pad-see-ew", "Pad See Ew", "Thai", 25, "Chewy wide noodles caramelised with chicken, egg, and Chinese broccoli.", ["400 g fresh wide rice noodles", "200 g chicken, thinly sliced", "2 eggs", "2 cups Chinese broccoli or bok choy", "1 tbsp dark soy sauce", "1.5 tbsp light soy sauce", "1 tbsp oyster sauce", "1 tsp sugar", "2 tbsp neutral oil"], ["Mix both soy sauces, oyster sauce, and sugar.", "Gently separate noodles with oiled fingers; do not tear them.", "Heat 1 tbsp oil on high. Cook chicken 5 minutes, then add greens for 1 minute; remove.", "Add remaining oil and eggs; scramble briefly.", "Add noodles and sauce. Leave untouched for 30 seconds, then toss.", "Return chicken and greens; toss for 1 minute."], "A very hot pan and brief pauses create caramelised edges instead of steamed noodles.", ["noodles", "chicken", "quick"]),
    recipe("mango-sticky-rice", "Mango Sticky Rice", "Thai", 40, "Sweet coconut sticky rice with ripe mango and a lightly salted sauce.", ["1 cup glutinous rice", "250 ml coconut milk", "1/3 cup sugar", "1/2 tsp salt", "2 ripe mangoes", "1 tsp cornflour", "1 tbsp sesame seeds"], ["Soak rice in plenty of water for at least 4 hours, then drain.", "Steam rice in a cloth-lined steamer for 25 minutes until translucent and chewy.", "Warm 200 ml coconut milk with sugar and half the salt until dissolved; do not boil.", "Pour over hot rice, cover, and rest 20 minutes.", "Warm remaining coconut milk with remaining salt and cornflour until slightly thick.", "Serve rice with sliced mango, coconut sauce, and sesame seeds."], "This requires glutinous rice; ordinary jasmine rice will not have the right texture.", ["dessert", "mango", "coconut"]),
]


def recipe_by_slug(slug):
    return next((recipe for recipe in RECIPES if recipe["slug"] == slug), None)
